'use client';
/**
 * Palantir Foundry Code Generation
 * Converts visual pipeline nodes into Foundry-compatible code/configs
 */

import type { PipelineNode, Connector, Field } from '@/lib/pipeline-data';

export interface OntologyExport {
  objectTypes: Record<string, { name: string; description: string; properties: Record<string, { type: string; description: string }> }>;
  linkTypes: Record<string, { from: string; to: string; cardinality: string }>;
  actionTypes: Record<string, { name: string; parameters: string[]; outputType: string }>;
}

const TYPE_MAP: Record<string, string> = {
  string: 'string',
  number: 'double',
  integer: 'long',
  boolean: 'boolean',
  date: 'timestamp',
  timestamp: 'timestamp',
};

function mapFoundryType(type: string): string {
  return TYPE_MAP[type.toLowerCase()] || 'string';
}

function deriveObjectName(node: PipelineNode): string {
  const name = (node.name || '').replace(/\s+/g, '');
  return name.charAt(0).toUpperCase() + name.slice(1) + '_' + node.id.substring(0, 6);
}

export function generateOntologyFromPipeline(nodes: PipelineNode[], connectors: Connector[]): OntologyExport {
  const objectTypes: OntologyExport['objectTypes'] = {};
  const linkTypes: OntologyExport['linkTypes'] = {};
  const actionTypes: OntologyExport['actionTypes'] = {};

  for (const node of nodes) {
    const fields: Field[] = (node.outputFields || node.inputFields || []);
    const objName = deriveObjectName(node);

    if (fields.length > 0) {
      const props: Record<string, { type: string; description: string }> = {};
      for (const field of fields) {
        props[field.name] = {
          type: mapFoundryType(field.type),
          description: `Auto-generated property for ${field.name}`,
        };
      }
      objectTypes[objName] = {
        name: objName,
        description: `Data object representing '${node.name || node.id}'`,
        properties: props,
      };
    }

    if (node.type === 'transformation') {
      const actionName = objName + 'Action';
      const params = fields.slice(0, 3).map((f: Field) => f.name);
      actionTypes[actionName] = { name: actionName, parameters: params, outputType: objName };
    }

    for (const conn of connectors.filter(c => c.from === node.id || c.to === node.id)) {
      const fromN = nodes.find(n => n.id === conn.from);
      const toN = nodes.find(n => n.id === conn.to);
      if (fromN && toN) {
        const fromObj = (fromN.name || '').replace(/\s+/g, '') + '_DS';
        const toObj = (toN.name || '').replace(/\s+/g, '') + '_DS';
        const k = fromObj + '_to_' + toObj;
        linkTypes[k] = { from: fromObj, to: toObj, cardinality: 'one_to_many' };
      }
    }
  }

  return { objectTypes, linkTypes, actionTypes };
}

export function generateOntologyJSON(nodes: PipelineNode[], connectors: Connector[]): string {
  return JSON.stringify(generateOntologyFromPipeline(nodes, connectors), null, 2);
}

export function generateTransformsCode(nodes: PipelineNode[]): string {
  let code = '# Foundry Transforms - Auto-generated by DataFlow Canvas\n\n';
  code += 'from transforms.api import transform, Input, Output\n';
  code += 'import pyspark.sql.functions as F\n\n\n';

  for (const [i, node] of nodes.entries()) {
    const nodeName = (node.name || 'node_' + i).replace(/\s+/g, '_').toLowerCase();
    const operation = node.operation;
    const opType = operation?.type || 'no_op';
    const s = (operation?.settings ?? {}) as Record<string, unknown>;

    code += `@transform(\n    output=Output("/Foundry/Projects/dataflowcanvas/${nodeName}"),\n    input_ds=Input("/Foundry/Projects/dataflowcanvas/${nodeName}_input")\n)\n`;
    code += `def compute_${nodeName}(output, input_ds):\n`;

    switch (opType) {
      case 'filter': {
        const f = (s.field as string) || 'col';
        const op = (s.operator as string) || '==';
        const v = s.value ?? '0';
        const sparkOp = op === '==' ? '==' : op === '!=' ? '!=' : op === '>' ? '>' : op === '<' ? '<' : '==';
        code += `    """Filter: where ${f} ${op} ${v}."""\n`;
        code += `    df = input_ds.dataframe()\n`;
        code += `    output.write_dataframe(df.filter(F.col("${f}") ${sparkOp} ${v}))\n\n\n`;
        break;
      }
      case 'join': {
        const jt = (s.joinType as string) || 'inner';
        code += `    """Join (${jt}) transform."""\n`;
        code += `    df = input_ds.dataframe()\n`;
        code += `    right_ds = spark.read.format("foundry").load("/Foundry/Projects/dataflowcanvas/${nodeName}_right")\n`;
        code += `    output.write_dataframe(df.join(right_ds, how="${jt}"))\n\n\n`;
        break;
      }
      case 'group_by': {
        const fields = ((s.groupByFields as string[]) || []).join(', ') || 'col';
        code += `    """Group By: ${fields}."""\n`;
        code += `    df = input_ds.dataframe()\n`;
        code += `    output.write_dataframe(df.groupBy(${fields}).count())\n\n\n`;
        break;
      }
      case 'sort': {
        const conds = (s.conditions as { field: string; direction?: string }[]) || [];
        const orderFields = conds.map(c => `F.col("${c.field}")${c.direction === 'desc' ? '.desc()' : ''}`).join(', ') || 'col';
        code += `    """Sort: order by ${orderFields}."""\n`;
        code += `    df = input_ds.dataframe()\n`;
        code += `    output.write_dataframe(df.orderBy(${orderFields}))\n\n\n`;
        break;
      }
      case 'select_columns': {
        const cols = ((s.selectedFields as string[]) || []).map((c: string) => `"${c}"`).join(', ') || '"*"';
        code += `    """Select columns."""\n`;
        code += `    df = input_ds.dataframe()\n`;
        code += `    output.write_dataframe(df.select(${cols}))\n\n\n`;
        break;
      }
      case 'deduplication': {
        code += `    """Deduplication."""\n`;
        code += `    output.write_dataframe(input_ds.dataframe().dropDuplicates())\n\n\n`;
        break;
      }
      case 'handle_missing_values': {
        code += `    """Handle missing values."""\n`;
        code += `    output.write_dataframe(input_ds.dataframe().dropna())\n\n\n`;
        break;
      }
      default:
        code += `    """Transform (${opType})."""\n`;
        code += `    output.write_dataframe(input_ds.dataframe())\n\n\n`;
    }
  }
  return code;
}

export function generatePipelineConfig(nodes: PipelineNode[], connectors: Connector[]): string {
  const config = {
    pipelineName: 'DataFlowCanvas-AutoGenerated',
    description: 'Pipeline generated by DataFlow Canvas',
    schedule: 'ON_TRIGGER',
    nodes: nodes.map((n, i) => ({
      id: n.id,
      name: (n.name || 'node_' + i).replace(/\s+/g, '_').toLowerCase(),
      type: n.type === 'source' ? 'input' : n.type === 'destination' ? 'output' : 'transform',
    })),
    dependencies: connectors.map(c => ({ from: c.from, to: c.to })),
  };
  return JSON.stringify(config, null, 2);
}
